# FILE: docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chopp-delivery
    ports:
      - "4321:4321"
      - "8787:8787"
    volumes:
      - ./.wrangler:/app/.wrangler
      - ./uploads:/app/uploads
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4321
      - PUBLIC_R2_URL=https://pub-59d8b8edbc6f497984f8a95046b2263b.r2.dev
    command: npm run dev --host 0.0.0.0
    restart: unless-stopped