name = "chopp-delivery"
main = "dist/_worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "chopp_delivery_db"
database_id = "1c6da776-060b-4cda-82d4-0d34c0641c42"

# R2 Storage
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "chopp-delivery-images"

# KV Storage
[[kv_namespaces]]
binding = "CACHE"
id = "fb68feaa56914ce8bef612ccfad2f2a8"

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "production"
